name: accu_weather_api
description: A Dart API Client for the AccuWeather API.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.5.0
 
dev_dependencies:
  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  mocktail: ^0.3.0
  test: ^1.21.3